version: '3'

services:
  overview:
    build: ../overview
    image: overview
    environment:
      - MONGO_ADDRESS=mongo
      - REDIS_ADDRESS=redis
    depends_on:
      - 'mongo'
      - 'redis'
    ports:
      - 3002:3002
  
  proxy:
    build: .
    image: proxy
    environment:
      - OVERVIEW_ADDRESS=overview
    depends_on:
      - 'overview'
      - 'mongo'
      - 'redis'
    ports:
      - 3000:3000

  mongo:
    image: mongo:3.6
    volumes:
      - overview-db:/var/lib/docker
  
  redis:
    image: redis:3.2-alpine

volumes:
  overview-db: